# -*- coding: utf-8 -*-
"""Heart_dataAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n2E2hSsCXaO_El69xN55pTGy6u05-tZw

1. Import The Libraries And Dataset
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('/content/drive/MyDrive/ML_Datasets/heart1.csv')

"""2. Display Top 5 Rows of The Dataset

"""

data.head(5)

"""3. Check The Last 5 Rows of The Dataset"""

data.tail(5)

"""4. Find Shape of Our Dataset (Number of Rows And Number of Columns)"""

data.shape

print("Number of Rows:", data.shape[0])
print("Number of Columns:", data.shape[1])

"""5. Get Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement"""

data.info()

"""6. Check Null Values In The Dataset

"""

data.isnull().sum()

"""7. Check For Duplicate Data and Drop Them"""

data_dup = data.duplicated().any()
print(data_dup)

data = data.drop_duplicates()

data.shape

"""8. Get Overall Statistics About The Dataset"""

#describe method
data.describe()

"""10. How Many People Have Heart Disease, And How Many Don't Have Heart Disease In This Dataset?"""

data.columns

p= data['target'].value_counts()
print(p)

sns.countplot(data=data,x=data['target'])

"""11. Find Count of Male & Female in this Dataset"""

data.columns

data['sex'].value_counts()

sns.countplot(data=data,x=data['sex'])
plt.xticks([0,1],['Female', 'Male'])
plt.show()

"""12. Find Gender Distribution According to The Target Variable"""

sns.countplot(x='sex',hue="target",data=data)
plt.xticks([1,0],['Male','Female'])
plt.legend(labels = ['No-Disease','Disease'])
plt.show()

"""13. Check Age Distribution In The Dataset"""

sns.displot(data['age'],bins=20)
plt.show()

"""14. Check Chest Pain Type

chest pain type(4 Values)

a. value 0 : typical angina

b. value 1 : atypical angina

c. value 2 : non-anginal pain

d. value 3 : asymptomatic
"""

sns.countplot(data=data,x=data['cp'])
plt.xticks([0,1,2,3],["typical angina", "atypical angina", "non-anginal pain","asymptomatic"])
plt.xticks(rotation=75)
plt.show()

"""15. Show The Chest Pain Distribution As Per Target Variable"""

data.columns

sns.countplot(x="cp", hue="target", data=data)
plt.legend(labels = ['No-Disease','Disease'])
plt.show()

"""16. Show Fasting Blood Sugar Distribution According To Target Variable"""

sns.countplot(x="fbs", hue="target", data=data)
plt.legend(labels = ['No-Disease','Disease'])
plt.show()

"""17. Check Resting Blood Pressure Distribution"""

data['trestbps'].hist()

"""18. Compare Resting Blood Pressure As Per Sex Column

19. Show Distribution of Serum cholesterol
"""

data['chol'].hist()

"""20. Plot Continuous Variables"""

cate_val=[]
cont_val=[]

for column in data.columns:
    if data[column].nunique() <=10:
        cate_val.append(column)
    else:
        cont_val.append(column)

cate_val

cont_val

data.hist(cont_val,figsize=(15,6))
plt.tight_layout()
plt.show()